# Generated by Django 5.2.2 on 2025-06-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0002_message_edited_messagehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='edited_at',
            new_name='created_at',
        ),
    ]
