# Generated by Django 5.2 on 2025-06-15 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0003_rename_edited_at_messagehistory_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='created_at',
            new_name='edited_at',
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
