pipeline {
    agent any
    
    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/peterkahumu/alx-backend-python.git',
                        credentialsId: 'github-credentials'
                    ]]
                ])
            }
        }

        stage('Set up venv') {
            steps {
                sh 'python3 -m venv $VENV'
                sh './$VENV/bin/pip && pip3 install --upgrade pip'
                sh './$VENV/bin/pip && pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './$VENV/bin/pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline Complete'
        }
    }
}

// git branch