pipeline {
    agent any

    environment {
        IMAGE_NAME = 'your-dockerhub-username/messaging-app'
        TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/peterkahumu/alx-backend-python.git',
                        credentialsId: 'github-credentials'
                    ]]
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME:$TAG messaging_app/"
            }
        }

        stage('Run Tests in Docker') {
            steps {
                sh "docker run --rm --entrypoint '' $IMAGE_NAME:$TAG pytest messaging_app/tests --junitxml=report.xml"
            }
        }


        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                    sh "docker push $IMAGE_NAME:$TAG"
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline Complete'
        }
    }
}
